# <src in repo>  <destination>  <os: any|macos|linux>

nvim              ~/.config/nvim              any
zsh/zshrc         ~/.zshrc                    any
tmux/tmux.conf    ~/.tmux.conf                any
starship.toml     ~/.config/starship.toml     any
lazygit           ~/.config/lazygit           any

# macOS-only tools with no Linux equivalent
karabiner         ~/.config/karabiner         macos
hammerspoon       ~/.hammerspoon              macos
