##########
# prompt #
##########
autoload -Uz add-zsh-hook vcs_info

setopt prompt_subst

add-zsh-hook precmd vcs_info

# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html
# %s - the current version control system, like git or svn
# %r - the name of the root directory of the repository
# %S - the current path relative to the repository root directory
# %b - branch information, like master
# %m - in case of Git, show information about stashes
# %u - show unstaged changes in the repository
# %c - show staged changes in the repository
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' use-simple true
zstyle ':vcs_info:git+set-message:*' hooks git-untracked
zstyle ':vcs_info:git*:*' formats '⎇ %F{13}%b%f %m%c%u'     # default ' (%s)-[%b]%c%u-'
zstyle ':vcs_info:git*:*' actionformats '[%b|%a%m%c%u]'   # default ' (%s)-[%b|%a]%c%u-'

PROMPT='
%F{yellow}[%*]%f %B%F{cyan}%~%f%b
%(?.%F{green}⚡.%F{red}⚡)%f'

RPROMPT='${vcs_info_msg_0_}'


#########################
# environment variables #
#########################

export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export MYSQLROOT=/usr/local/opt/mysql-client
# For bash or zsh
export GO111MODULE=on
export LOCAL_CT_DEV="true"
export CT_SERVICE_USER_SUFFIX="-"$USER
export CT_ENV="aws"
export AZURE_TENANT_APP_IDS_BY_DOMAIN="stratusinternal.onmicrosoft.com:f7cba484-65f3-43e8-8696-123e1f9b9586,stratustinternalgov.onmicrosoft.com:b3e0cb3e-adbd-4e0e-8160-804e8e2a89af"
export AZURE_TENANT_CLIENT_SECRETS_BY_DOMAIN="stratusinternal.onmicrosoft.com:nOeOFleg7cFWRAxHfHsjmyRSJU+Yg35eg3IwZpf9OHo=,stratusinternalgov.onmicrosoft.com:IWK-SOqaS6iLFB2@b]C=lq1xM0GuV/-0"
export AZURE_EA_CLIENT_SECRET="E.*q6pu/g3F?yVZZq58OsFvygF0mhUrF"
export AZURE_TENANT_APP_ID=f7cba484-65f3-43e8-8696-123e1f9b9586
export AZURE_TENANT_CLIENT_SECRET=nOeOFleg7cFWRAxHfHsjmyRSJU+Yg35eg3IwZpf9OHo=
export POLICY_LIBRARY_URL=https://norlabs-resource-library-staging.s3.amazonaws.com
export CLOUD_CUSTODIAN_BIN=~/custodian/bin/
export NSQ_HOST=127.0.0.1
export NSQ_LOOKUPDHOSTS=127.0.0.1
export WEBAPI_SERVICE_HOST=localhost
export WEBAPI_SERVICE_PORT=8081

# GitLab vscode extension settings
export GITLAB_WORKFLOW_INSTANCE_URL=https://git.kion.io/
export GITLAB_WORKFLOW_TOKEN=glpat-fdFGBCosr8vhyyzsLuWg

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$GOROOT/bin:$MYSQLROOT/bin:/usr/local/go/bin:$GOPATH/bin:/Users/kevinschmincke/.nimble/bin:$PATH

# Load Angular CLI autocompletion.
# source <(ng completion script)
export PATH="/usr/local/opt/jpeg/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/jpeg/lib"
export CPPFLAGS="-I/usr/local/opt/jpeg/include"
export PKG_CONFIG_PATH="/usr/local/opt/jpeg/lib/pkgconfig"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="/usr/local/opt/jpeg/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/jpeg/lib"
export CPPFLAGS="-I/usr/local/opt/jpeg/include"
export PKG_CONFIG_PATH="/usr/local/opt/jpeg/lib/pkgconfig"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/mysql-client/lib"
export CPPFLAGS="-I/usr/local/opt/mysql-client/include"
export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig"






###########
# aliases #
###########

# global aliases
alias -g G='| grep'
alias -g L='| less'
alias -g M='| more'
alias -g H='| head'
alias -g T='| tail'

alias zshconfig="nvim ~/.zshrc"
alias zshrc="nvim ~/.zshrc"
alias source-zshrc="source ~/.zshrc"
# alias ls="colorls --sort-dirs"
# alias la="colorls --sort-dirs -a"
# alias lst="colorls --tree"
# alias lsgs="colorls --gs --sort-dirs"
# alias lsgst="colorls --gs --tree"

# git aliases
alias gs="git status"
alias gst="git status"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gcm="git commit -m"
alias gcam="git commit -am"

function get_current_branch() {
  git branch --show-current
}

alias ggpull='git pull origin "$(get_current_branch)"'
alias ggpush='git push origin "$(get_current_branch)"'
alias echobranch='echo "$(get_current_branch)"'

alias psg="ps -ef | grep -v grep | grep"

pidport_func() {
  lsof -n -i4TCP:$1 | grep LISTEN | awk '{print $2}'
}

alias pidport='pidport_func'

# fix mouse when gesture buttons aren't working
# just restarts the logi options+ process, but
# I'll never remember the command otherwise
alias fixmouse='killall -9 logioptionsplus_agent'

# npm aliases
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
alias ni="npm install"
alias nci="npm ci"
alias ns="npm start"
alias sb="npm run storybook"

# portal directory aliases
export MY_KION_DIR=~/dev/kion/portal
alias webapi="cd $MY_KION_DIR/src/app/webapi"
alias client="cd $MY_KION_DIR/src/app/webui/client"
alias portal="cd $MY_KION_DIR"
alias ui="client"

# portal webapi migrate/reset commands
alias dbreset="portal && make db-reset-full-demo-data && webapi && go build && ./webapi"
alias dbmigrate="portal && make db-migrate && webapi && go build && ./webapi"
alias dbconnect="mysql -u root -h 127.0.0.1 -p"

# don't accidentally open vim instead of neovim
alias vim="nvim"
alias vi="nvim"

# If you need to run the webapi with licensing turned on, you can run this:
# go build src/webapi/main.go -ldflags "-X cloudtamer.io/infrastructure/globalconst.enableLicensing=true"

eval "$(direnv hook zsh)"


