#########################
# environment variables #
#########################

export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export MYSQLROOT=/usr/local/opt/mysql-client
# For bash or zsh
export GO111MODULE=on
export LOCAL_CT_DEV="true"
export CT_SERVICE_USER_SUFFIX="-"$USER
export CT_ENV="aws"
export AZURE_TENANT_APP_IDS_BY_DOMAIN="stratusinternal.onmicrosoft.com:f7cba484-65f3-43e8-8696-123e1f9b9586,stratustinternalgov.onmicrosoft.com:b3e0cb3e-adbd-4e0e-8160-804e8e2a89af"
export AZURE_TENANT_CLIENT_SECRETS_BY_DOMAIN="stratusinternal.onmicrosoft.com:nOeOFleg7cFWRAxHfHsjmyRSJU+Yg35eg3IwZpf9OHo=,stratusinternalgov.onmicrosoft.com:IWK-SOqaS6iLFB2@b]C=lq1xM0GuV/-0"
export AZURE_EA_CLIENT_SECRET="E.*q6pu/g3F?yVZZq58OsFvygF0mhUrF"
export AZURE_TENANT_APP_ID=f7cba484-65f3-43e8-8696-123e1f9b9586
export AZURE_TENANT_CLIENT_SECRET=nOeOFleg7cFWRAxHfHsjmyRSJU+Yg35eg3IwZpf9OHo=
export POLICY_LIBRARY_URL=https://kion-resource-library.s3.amazonaws.com/
export CLOUD_CUSTODIAN_BIN=~/custodian/bin/
export NSQ_HOST=127.0.0.1
export NSQ_LOOKUPDHOSTS=127.0.0.1
export WEBAPI_SERVICE_HOST=localhost
export WEBAPI_SERVICE_PORT=8081

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$GOROOT/bin:$MYSQLROOT/bin:/usr/local/go/bin:$GOPATH/bin:/Users/kevinschmincke/.nimble/bin:/Applications/WezTerm.app/Contents/MacOS:$PATH

# Load Angular CLI autocompletion.
# source <(ng completion script)
export PATH="/usr/local/opt/jpeg/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/jpeg/lib"
export CPPFLAGS="-I/usr/local/opt/jpeg/include"
export PKG_CONFIG_PATH="/usr/local/opt/jpeg/lib/pkgconfig"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="/usr/local/opt/jpeg/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/jpeg/lib"
export CPPFLAGS="-I/usr/local/opt/jpeg/include"
export PKG_CONFIG_PATH="/usr/local/opt/jpeg/lib/pkgconfig"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/mysql-client/lib"
export CPPFLAGS="-I/usr/local/opt/mysql-client/include"
export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig"

export CLICOLOR=true
export VISUAL=nvim
export EDITOR=nvim





###########
# aliases #
###########

# global aliases
alias -g G='| grep'
alias -g L='| less'
alias -g H='| head'
alias -g T='| tail'

alias zshconfig="nvim ~/.zshrc"
alias zshrc="nvim ~/.zshrc"
alias so="source ~/.zshrc"
# alias ls="colorls --sort-dirs"
# alias la="colorls --sort-dirs -a"
# alias lst="colorls --tree"
# alias lsgs="colorls --gs --sort-dirs"
# alias lsgst="colorls --gs --tree"

# git aliases
alias gs="git status"
alias gst="git status"
alias gcb="git checkout -b"
alias gcm="git commit -m"
alias gcam="git commit -am"

# checkout branch with fzf
alias gco="git branch --sort=-committerdate | grep -v '^*' | fzf --height=20% --reverse --info=inline | xargs git checkout";


function get_current_branch() {
  git branch --show-current
}

alias ggpull='git pull origin "$(get_current_branch)"'
alias ggpush='git push origin "$(get_current_branch)"'
alias echobranch='echo "$(get_current_branch)"'

alias psg="ps -ef | grep -v grep | grep"

pidport_func() {
  lsof -n -i4TCP:$1 | grep LISTEN | awk '{print $2}'
}

alias pidport='pidport_func'

# fix mouse when gesture buttons aren't working
# just restarts the logi options+ process, but
# I'll never remember the command otherwise
alias fixmouse='killall -9 logioptionsplus_agent'

# npm aliases
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
alias ni="npm install"
alias nci="npm ci"
alias ns="npm start"
alias sb="npm run storybook"

# portal directory aliases
export MY_KION_DIR=~/dev/kion/portal
alias webapi="cd $MY_KION_DIR/src/app/webapi"
alias client="cd $MY_KION_DIR/src/app/webui/client"
alias portal="cd $MY_KION_DIR"
alias ui="client"

# portal webapi migrate/reset commands
alias dbreset="portal && make db-reset-full-demo-data && webapi && go build && ./webapi"
alias dbmigrate="portal && make db-migrate && webapi && go build && ./webapi"
alias dbconnect="mysql -u root -h 127.0.0.1 -p"

# don't accidentally open vim instead of neovim
alias vim="nvim"
alias vi="nvim"

# If you need to run the webapi with licensing turned on, you can run this:
# go build src/webapi/main.go -ldflags "-X cloudtamer.io/infrastructure/globalconst.enableLicensing=true"

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

